### ISSUE TITLE
Define how moderating a room by stopping unwanted servers from participating

### ISSUE THREAD

**Issue by amandahla** [canonical/synapse-operator#104]
#### What would you like to do?

Prevent my public room from unwanted specific servers.

#### Why would you like to do it?
Create specific rules for joining.

#### How would you like to achieve it?
API or UI

### Additional context

Related:
Server ACLs
https://matrix.org/docs/older/moderation/
https://spec.matrix.org/v1.8/client-server-api/#server-access-control-lists-acls-for-rooms

Public room option
![image](https://github.com/canonical/synapse-operator/assets/12564014/7a039ca4-b0f1-4e7b-b44b-a13bdae7d2a3)

**Comment by TheArcaneBrony** [comment]
This is possible via the `m.room.server_acls` event.
This can easily be managed by using Draupnir/Mjolnir (`m.policy.rule.server`/Server policy events).

This is still the de-facto way of managing server bans, and *should* be used in a blocklist fashion, rather than allowlist, given that many may be using their own servers to communicate.

**Comment by amandahla** [comment]
> This is possible via the `m.room.server_acls` event, as linked in the "related" section. This can easily be managed by using Draupnir/Mjolnir (`m.policy.rule.server`/Server policy events).
> 
> This is still the de-facto way of managing server bans, and _should_ be used in a blocklist fashion, rather than allowlist, given that many may be using their own servers to communicate.

Nice, thanks!

**Comment by amandahla** [comment]
Closing the issue since it no longer applies.
